### PR TITLE
Clean and standardize example notebooks

### PR DESCRIPTION
**Pull request by Okroshiashvili**
## Description

Clean and standardize example notebooks. Update them to be compatible with the latest version of Orbit. Fix some typos as well.

### CODE REVIEW

**Comment by Okroshiashvili** [comment]
Hey @edwinnglabs and @wangzhishi . I followed the contribution guide but I was not able to push the commit due to access denial. Then, I forked the repo and send PR that way. If this is not the correct way, please tell me how to do it in the correct way.

Please, review my PR :)

**Comment by Okroshiashvili** [comment]
I think I solved the access problem. Closing this PR and will send a new one. Sorry for that bustling

**Comment by wangzhishi** [comment]
> Hey @edwinnglabs and @wangzhishi . I followed the contribution guide but I was not able to push the commit due to access denial. Then, I forked the repo and send PR that way. If this is not the correct way, please tell me how to do it in the correct way.
> 
> Please, review my PR :)
> 
> **Update:**
> 
> I tried to clone repo with SSH and then tried to send PR again but still got the `ERROR: Permission to uber/orbit.git denied to Okroshiashvili. fatal: Could not read from remote repository.`

Hi @Okroshiashvili , it is good to send the PR from a forked repo. You updates look good to me. The only thing is that the output is sort of length when fitting a Stan model. Maybe it is because you used the Conda environment. I refreshed the notebooks, and also fixed some newly spotted bugs. Now the PR is good to merge to the `dev` branch.

Thanks again, and welcome to be a contributor of orbit.

**Review by wangzhishi — APPROVED** [review]
LGTM

**Comment by Okroshiashvili** [comment]
Thanks, @wangzhishi for your comment and help. I'll consider it definitely. Moreover, I spotted some bugs as well and will work to fix them. But, until that, I want to fix #439

**Pull request merged**
