### PR TITLE
Update tutorials notebooks

### PR DESCRIPTION
**Pull request by ppstacy**
## Description

Please include a summary of the change and which issue is fixed.

Fixes # 309
1. Updated tutorials:
- quick start for LGT and DLT
- utilities for simulation data generation 

2. Add tox.int for linting
3. Fix lint issues in code
4. Add encoding type when compiling the stan file

### CODE REVIEW

**Comment by ppstacy** [comment]
Added the [notebook](examples/Regression.ipynb) and [iclaims](examples/data/iclaims_example_v2.csv) dataset for regression.
For regression with the iclaims data, I tested two versions:

- Using the full data from Jan 2010 to Jan 2020:  it didn't help much after adding regressor
image

- Using the data from Jan 2018 to Jan 2020: this is because of the google trend term unemploy with a more clear trend vs.. job claims (chart in the notebook); results look better after this but still, it's very hard to predict the peak but much more close in the second half in 2020 comparing with the one not using regression.
image

Should we keep both or only one of these? How do you think @edwinnglabs, @wangzhishi?
Also please note that I just update the notebooks under docs/tutorials/ and haven't updated the page via Sphinx. I probably will do that in a new PR for all the tutorials after we approved this. Thanks!

**Comment by edwinnglabs** [comment]
@ppstacy since the covid has a unprecedented change on the claims, i won't be surprised using a simple seasonal model nor a regression model can perfectly predict claims way before covid happens.  I would just predicting the recovery by reducing forecast length to say 26.  We can also explore indices like VIX and SP500.  My guess is that it may not be perfect but should improve from a non-regression model.

**Comment by ppstacy** [comment]
Thanks @edwinnglabs for helping to work on this together. I've updated the notebook and data load function as we discussed offline. Thanks!

**Comment by edwinnglabs** [comment]
@ppstacy posting the notebook link [here](https://nbviewer.jupyter.org/github/uber/orbit/blob/d0b89757392e4423a629a67282961e84d2e1d923/docs/tutorials/regression.ipynb) 

Did you try using sigma prior = 10
[optional] and some positive coef for beta prior say .1?

**Comment by edwinnglabs** [comment]
@ppstacy also, I notice in LGT, we didn't run a seaonal model in `LGTFull`.  Is that intentional?

**Review by edwinnglabs — CHANGES_REQUESTED** [review]
@ppstacy Please review see if the changes make sense
@wangzhishi Please do a final review since it may also impact other notebooks

**Review by ppstacy — COMMENTED** [review]
@edwinnglabs Thank you so much for making all the changes!! 

A quick question here for standardization. Since we have the filter at the bottom to return data by date, should we do all the transformation after it?

**Comment by ppstacy** [comment]
> @ppstacy also, I notice in DLT, we didn't run a seasonal model in `DLTFull`. Is that intentional?
> 
> I made some update with my last PR as such:
> 
> 1. re-write some wordings on dataset explanations
> 2. fix a potential problem of using non-seasonal model in DLT
> 3. refine the regression example a bit; **please review**
> 4. the dataset should be uploaded to master in a separate PR

For #2, I probably forgot to put the seasonality there. Thanks for catching it. 
For #3, I reviewed all the changes, it looks great. It makes more clear after adding SMAPE results.

Maybe I can work on #4 and update the tutorials page via Sphinx after we merge this PR? Thanks!

**Comment by edwinnglabs** [comment]
> > @ppstacy also, I notice in DLT, we didn't run a seasonal model in `DLTFull`. Is that intentional?
> > I made some update with my last PR as such:
> > 
> > 1. re-write some wordings on dataset explanations
> > 2. fix a potential problem of using non-seasonal model in DLT
> > 3. refine the regression example a bit; **please review**
> > 4. the dataset should be uploaded to master in a separate PR
> 
> For 2, I probably forgot to put the seasonality there. Thanks for catching it.
> For 3, I reviewed all the changes, it looks great. It makes more clear after adding SMAPE results.
> 
> Maybe I can work on 4 and update the tutorials page via Sphinx after we merge this PR? Thanks!

Sounds good.  Please submit a separate PR for the dataset merging onto master @ppstacy 
@wangzhishi could you also review this diff?

**Review by wangzhishi — APPROVED** [review]
LGTM

**Pull request merged**
