### PR TITLE
add unit tests to assert reproducibility of train and predict

### PR DESCRIPTION
**Pull request by steveyang90**
## Description

To address the issue of model reproducibility with a given seed, this PR adds a more strict unit test. No functionality is changed in the package as the results were already fully reproducible with a seed.

## Type of change

Please delete options that are not relevant.

- [ ] New feature

## How Has This Been Tested?

Adds a unit test to assert model training **and** model prediction is reproducible with a seed for `LGTFull`.
The test creates two instances of `LGTFull` and runs `fit()` and `predict()` for each instance.

Assertions check that every value of `LGTFull._posterior_samples` is identical in the two instances along with every value returned by `LGTFull.predict()`.

Unit test is parametrized for both `StanEstimatorMCMC` and `StanEstimatorVI`,  mixed regressor signs, and with seasonality values `1` and `52`

### CODE REVIEW

**Comment by steveyang90** [comment]
@wangzhishi after digging into #285 a little further, it appears to me that the model results are actually fully reproducible on my end. Please review new unit test and let me know if you have a different way you tested that is still raising reproducibility issues!

I can also include for `DLTFull` after review

**Comment by wangzhishi** [comment]
@steveyang90 thanks for adding this unit test. The workflow setup in your unit test indeed gives the same prediction results on `test_df`. Your test also proves that the global random seed is taking effect.

 My previous argument is mainly for this scenario: say we only have one model `lgt_first`. Calling this model object to do prediction twice on the same `test_df` gave different results:

```
predict_df_first = lgt_first.predict(test_df)
predict_df_second = lgt_first.predict(test_df)
# predict_df_first not same as predict_df_second
```
so, if users want to reproduce the predictions, they would have to instantiate the model object again and re-do the training and prediction. My previous thought is that if we can allow a random seed in the predict mode to reproduce the predictions w/o refitting. 

With this said, do you think it is still necessary? Sorry that I didn't make my previous claim more clear. 

FYI @edwinnglabs

**Comment by steveyang90** [comment]
No worries @wangzhishi, I think this actually brings up a really good nuance in the workflow that we hadn't thought through. 

I see the benefit of being able to call `predict()` twice on an already instantiated object, but I see some tradeoffs here if there is a case where we'd want the noise generated in `predict()` to be different on each call.

Suppose for example, we have multiple `test_df`s with different feature values that we run prediction on from a single trained instance. That means that the noise we'd generate on each prediction is actually identical if we set a seed for each predict. I'm not sure if that is necessarily what we want? I guess from a practical standpoint, it will still appear random, but we'd be including identical noise to the predictions.

We can leave #285 open to discuss further nuances if we need after this PR, but I think implementing will require thinking through all use cases.

**Review by wangzhishi — APPROVED** [review]
LGTM

**Comment by wangzhishi** [comment]
sounds good. accepted the PR for the unit test.

**Pull request merged**
