### PR TITLE
Simple Bayesian linear model

### LINKED ISSUE #423: Implement simple Bayesian linear model
**Is your feature request related to a problem? Please describe.**
Currently the time series models implemented in Orbit are a kind of complicated. It would be great to have some simpler Bayesian models, which would be useful for:
- some simple forecasting tasks
- as baseline performance to be compared to more sophisticated models in Orbit
- as a demo on how to implement models in Orbit
- as a basic template models for sophisticated Bayesian models to be implemented in.

**Describe the solution you'd like**
Implement the most basic Bayesian linear model in Orbit. Progressively adding more time series related structures on it.

**Describe alternatives you've considered**
Beside building from scratch, we may also try to trim down those existing implementations such as DLT or LGT, but currently they are too complicated in the codes.

### PR DESCRIPTION
**Pull request by pochoi**
## Description

Implementation of simple Bayesian linear model. Currently in Stan only. (in Pyro in near future)
The model is the most basic Bayesian linear regression with all default non-informative priors in regression coefficients and error.

Fixes #423 

## Type of change

- [x] New feature
- [ ] This change requires a documentation update

## How Has This Been Tested?

A few unit tests are written, with respect to initialization, StanMCMC, StanMAP.

### CODE REVIEW

**Comment by edwinnglabs** [comment]
is it possible to expand the scope to cover #274 ?

**Comment by pochoi** [comment]
What would be the exact scope of issue #274 ? 
What "trend" means in #274 exactly?
I can see also in the PR #275 related to #274 has some more somethings: positive/regular regressor, normal/double exponential/Cauchy prior. Are they implicit scope?

**Comment by edwinnglabs** [comment]
> What would be the exact scope of issue #274 ?
> What "trend" means in #274 exactly?
> I can see also in the PR #275 related to #274 has some more somethings: positive/regular regressor, normal/double exponential/Cauchy prior. Are they implicit scope?

My ask i think mainly for regularization.  for positive/regular, we can skip for now.

**Comment by pochoi** [comment]
> > What would be the exact scope of issue #274 ?
> > What "trend" means in #274 exactly?
> > I can see also in the PR #275 related to #274 has some more somethings: positive/regular regressor, normal/double exponential/Cauchy prior. Are they implicit scope?
> 
> My ask i think mainly for regularization. for positive/regular, we can skip for now.

One thing unique is the Stan and Pyro interfaces. Currently this PR only have Stan. If we add tons of different Stan priors at once, it may take some time to keep up the pyro part in future. I guess it is the reason why some models in Orbit only contains Stan estimators. Therefore, a better plan is to progressively build the models, instead of throwing in all fancy Stan things into it at once.

Also, having all fancy priors appear at once, it may not be a good demo of a basic model implementation in Orbit. Currently Orbit only contains aggressively customized models while neither the [Orbit paper ](https://arxiv.org/pdf/2004.08492.pdf)  
or the [Orbit documentation](https://orbit-ml.readthedocs.io/en/stable/index.html) contain details of the customization. 
A simple Bayesian linear regression with no fancy customization would be a better demo on model building in Orbit.

**Comment by pochoi** [comment]
A jupyter notebook `regression3.ipynb` is added.

The prediction of MAP is changed to use the variable `self._aggregate_posteriors['map']` instead of `self._posterior_samples`. However, there is a dummy dimension in `self._aggregate_posteriors['map']`. Therefore the `np.squeeze` is used to delete this dimension.

**Pull request closed without merging**
